package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/kampong/debate/internal/models"
)

// GenerateMarkdown produces a full markdown report from a debate session.
func GenerateMarkdown(session *models.DebateSession) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# %s\n\n", session.Topic))
	sb.WriteString(fmt.Sprintf("**Mode:** %s  \n", strings.Title(string(session.Mode))))
	sb.WriteString(fmt.Sprintf("**Date:** %s  \n", session.CreatedAt.Format(time.RFC1123)))
	sb.WriteString(fmt.Sprintf("**Status:** %s  \n", string(session.GetStatus())))
	sb.WriteString(fmt.Sprintf("**Agents:** %d  \n", len(session.Agents)))
	sb.WriteString(fmt.Sprintf("**Rounds:** %d  \n\n", session.Round))

	// Panel
	sb.WriteString("## Panel\n\n")
	sb.WriteString("| Agent | Role | Expertise |\n")
	sb.WriteString("|-------|------|-----------|\n")
	for _, a := range session.Agents {
		sb.WriteString(fmt.Sprintf("| %s %s | %s | %s |\n", a.Icon, a.Name, a.Role, a.Expertise))
	}
	sb.WriteString("\n")

	// Transcript
	if session.Mode == models.ModeDiscussion {
		sb.WriteString("## Discussion Transcript\n\n")
	} else {
		sb.WriteString("## Debate Transcript\n\n")
	}

	currentPhase := ""
	for _, entry := range session.Transcript {
		phase := string(entry.Phase)
		if phase != currentPhase {
			currentPhase = phase
			sb.WriteString(fmt.Sprintf("### %s\n\n", formatPhase(phase)))
		}

		if entry.QuestionText != "" {
			// Cross-exam question
			sb.WriteString(fmt.Sprintf("**%s** asked **%s**:\n\n", entry.AgentName, findAgentName(session.Agents, entry.TargetAgentID)))
			sb.WriteString(fmt.Sprintf("> %s\n\n", entry.QuestionText))
		} else if entry.Text != "" {
			sb.WriteString(fmt.Sprintf("#### %s %s\n", findAgentIcon(session.Agents, entry.AgentID), entry.AgentName))
			sb.WriteString(fmt.Sprintf("*%s · Round %d*\n\n", entry.AgentRole, entry.Round))
			sb.WriteString(entry.Text + "\n\n")
			if entry.SearchQuery != "" {
				sb.WriteString(fmt.Sprintf("<sub>🔍 Research: %s</sub>\n\n", entry.SearchQuery))
			}
		}
	}

	// Verdict or Synthesis
	if session.Mode == models.ModeDiscussion && session.GetSynthesis() != nil {
		writeDiscussionReport(&sb, session)
	} else if session.GetVerdict() != nil {
		writeDebateReport(&sb, session)
	}

	// Knowledge Graph Summary
	if len(session.Graph.Nodes) > 0 {
		sb.WriteString("---\n\n## Knowledge Graph Summary\n\n")
		sb.WriteString(fmt.Sprintf("**Nodes:** %d | **Edges:** %d\n\n", len(session.Graph.Nodes), len(session.Graph.Edges)))

		claims := filterNodes(session.Graph.Nodes, "claim")
		concepts := filterNodes(session.Graph.Nodes, "concept")
		evidence := filterNodes(session.Graph.Nodes, "evidence")

		if len(claims) > 0 {
			sb.WriteString("### Claims\n\n")
			for _, n := range claims {
				agent := n.AgentName
				if agent == "" {
					agent = "Unknown"
				}
				sb.WriteString(fmt.Sprintf("- **%s** — %s (*%s*)\n", n.Label, firstSentence(n.Content), agent))
			}
			sb.WriteString("\n")
		}
		if len(concepts) > 0 {
			sb.WriteString("### Concepts\n\n")
			for _, n := range concepts {
				sb.WriteString(fmt.Sprintf("- **%s**\n", n.Label))
			}
			sb.WriteString("\n")
		}
		if len(evidence) > 0 {
			sb.WriteString("### Evidence Sources\n\n")
			for _, n := range evidence {
				if n.SourceURL != "" {
					sb.WriteString(fmt.Sprintf("- [%s](%s)\n", n.Label, n.SourceURL))
				} else {
					sb.WriteString(fmt.Sprintf("- %s\n", n.Label))
				}
			}
			sb.WriteString("\n")
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by Kampong AI Debate Arena*\n")

	return sb.String()
}

func writeDebateReport(sb *strings.Builder, session *models.DebateSession) {
	v := session.GetVerdict()
	if v == nil {
		return
	}
	sb.WriteString("## Verdict\n\n")

	// Winner
	winner := findAgent(session.Agents, v.WinnerAgentID)
	if winner != nil {
		sb.WriteString(fmt.Sprintf("### 🏆 Winner: %s %s\n\n", winner.Icon, winner.Name))
	}

	// Scorecard
	if len(v.Scorecard) > 0 {
		sb.WriteString("### Scorecard\n\n")
		sb.WriteString("| Agent | Evidence | Logic | Novelty | Total |\n")
		sb.WriteString("|-------|----------|-------|---------|-------|\n")
		for _, s := range v.Scorecard {
			sb.WriteString(fmt.Sprintf("| %s | %.1f | %.1f | %.1f | **%.1f** |\n", s.AgentName, s.Evidence, s.Logic, s.Novelty, s.Total))
		}
		sb.WriteString("\n")
	}

	// Strongest evidence
	if v.StrongestEvidence.Claim != "" {
		sb.WriteString("### Strongest Evidence\n\n")
		agent := findAgent(session.Agents, v.StrongestEvidence.AgentID)
		agentName := "Unknown"
		if agent != nil {
			agentName = agent.Name
		}
		sb.WriteString(fmt.Sprintf("**%s** (%s): %s\n\n", v.StrongestEvidence.Claim, agentName, v.StrongestEvidence.Why))
	}

	// Consolidated claims
	if len(v.ConsolidatedClaims) > 0 {
		sb.WriteString("### Consolidated Findings\n\n")
		for _, c := range v.ConsolidatedClaims {
			icon := "•"
			switch c.Status {
			case "established":
				icon = "✅"
			case "contested":
				icon = "⚔️"
			case "disputed":
				icon = "❌"
			case "unresolved":
				icon = "❓"
			}
			sb.WriteString(fmt.Sprintf("- %s **%s** — %s\n", icon, strings.ToUpper(c.Status), c.Claim))
			if len(c.Support) > 0 {
				sb.WriteString(fmt.Sprintf("  - Supported by: %s\n", strings.Join(c.Support, ", ")))
			}
			if len(c.Oppose) > 0 {
				sb.WriteString(fmt.Sprintf("  - Opposed by: %s\n", strings.Join(c.Oppose, ", ")))
			}
		}
		sb.WriteString("\n")
	}

	// Turning points
	if len(v.TurningPoints) > 0 {
		sb.WriteString("### Key Turning Points\n\n")
		for _, t := range v.TurningPoints {
			sb.WriteString(fmt.Sprintf("- %s\n", t))
		}
		sb.WriteString("\n")
	}

	// Reasoning
	if v.Reasoning != "" {
		sb.WriteString("### Judge's Reasoning\n\n")
		sb.WriteString(v.Reasoning + "\n\n")
	}

	// Synthesis narrative
	if v.Synthesis != "" {
		sb.WriteString("### Debate Synthesis\n\n")
		sb.WriteString(v.Synthesis + "\n\n")
	}
}

func writeDiscussionReport(sb *strings.Builder, session *models.DebateSession) {
	syn := session.GetSynthesis()
	if syn == nil {
		return
	}
	sb.WriteString("## Discussion Synthesis\n\n")

	// Key Insights
	if len(syn.KeyInsights) > 0 {
		sb.WriteString("### Key Insights\n\n")
		for _, ins := range syn.KeyInsights {
			sb.WriteString(fmt.Sprintf("#### %s\n\n", ins.Theme))
			sb.WriteString(ins.Finding + "\n\n")
			if len(ins.SupportBy) > 0 {
				sb.WriteString(fmt.Sprintf("*Supported by: %s*\n\n", strings.Join(ins.SupportBy, ", ")))
			}
			if ins.Evidence != "" {
				sb.WriteString(fmt.Sprintf("> %s\n\n", ins.Evidence))
			}
		}
	}

	// Common Themes
	if len(syn.CommonThemes) > 0 {
		sb.WriteString("### Common Themes\n\n")
		for _, t := range syn.CommonThemes {
			sb.WriteString(fmt.Sprintf("- %s\n", t))
		}
		sb.WriteString("\n")
	}

	// Surprising Findings
	if len(syn.SurprisingFindings) > 0 {
		sb.WriteString("### Surprising Findings\n\n")
		for _, f := range syn.SurprisingFindings {
			sb.WriteString(fmt.Sprintf("- %s\n", f))
		}
		sb.WriteString("\n")
	}

	// Open Questions
	if len(syn.OpenQuestions) > 0 {
		sb.WriteString("### Open Questions\n\n")
		for _, q := range syn.OpenQuestions {
			sb.WriteString(fmt.Sprintf("- %s\n", q))
		}
		sb.WriteString("\n")
	}

	// Overview
	if syn.Overview != "" {
		sb.WriteString("### Overview\n\n")
		sb.WriteString(syn.Overview + "\n\n")
	}
}

// Helper functions

func formatPhase(phase string) string {
	phase = strings.ReplaceAll(phase, "_", " ")
	return strings.Title(phase)
}

func findAgent(agents []models.Agent, id string) *models.Agent {
	for _, a := range agents {
		if a.ID == id {
			return &a
		}
	}
	return nil
}

func findAgentName(agents []models.Agent, id string) string {
	a := findAgent(agents, id)
	if a != nil {
		return a.Name
	}
	return "Unknown"
}

func findAgentIcon(agents []models.Agent, id string) string {
	a := findAgent(agents, id)
	if a != nil {
		return a.Icon
	}
	return "🤖"
}

func filterNodes(nodes []models.GraphNode, nodeType string) []models.GraphNode {
	var filtered []models.GraphNode
	for _, n := range nodes {
		if n.Type == nodeType {
			filtered = append(filtered, n)
		}
	}
	return filtered
}

func firstSentence(s string) string {
	if s == "" {
		return ""
	}
	if idx := strings.Index(s, ". "); idx > 0 && idx < 200 {
		return s[:idx+1]
	}
	if len(s) > 200 {
		return s[:197] + "..."
	}
	return s
}

// MarkdownToHTML converts a markdown report to a styled HTML page for PDF printing.
func MarkdownToHTML(title string, md string) string {
	// Simple markdown to HTML conversion
	html := md
	// Headers
	for i := 3; i >= 1; i-- {
		prefix := strings.Repeat("#", i) + " "
		html = strings.ReplaceAll(html, prefix, fmt.Sprintf("<h%d>", i))
		// Close tags at newlines
		html = strings.ReplaceAll(html, fmt.Sprintf("</h%d>", i), fmt.Sprintf("</h%d>", i))
	}
	// Bold
	html = strings.ReplaceAll(html, "**", "</strong>")
	html = strings.ReplaceAll(html, "**", "<strong>")
	// Italic
	html = strings.ReplaceAll(html, "*", "</em>")
	html = strings.ReplaceAll(html, "*", "<em>")
	// Links
	// Tables - just render as preformatted for simplicity
	// Line breaks
	html = strings.ReplaceAll(html, "\n\n", "</p><p>")
	html = strings.ReplaceAll(html, "\n", "<br>")

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>%s — Kampong Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; line-height: 1.7; font-size: 14px; }
  h1 { font-size: 2em; border-bottom: 3px solid #6366f1; padding-bottom: 0.3em; margin-bottom: 0.5em; color: #1a1a2e; }
  h2 { font-size: 1.5em; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.3em; margin-top: 1.5em; color: #2d3748; }
  h3 { font-size: 1.2em; margin-top: 1.2em; color: #4a5568; }
  h4 { font-size: 1em; margin-top: 1em; color: #4a5568; }
  table { border-collapse: collapse; width: 100%%; margin: 1em 0; }
  th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
  th { background: #f7fafc; font-weight: 600; }
  blockquote { border-left: 3px solid #6366f1; margin: 1em 0; padding: 0.5em 1em; background: #f7fafc; color: #4a5568; }
  sub { color: #718096; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 2em 0; }
  a { color: #6366f1; text-decoration: none; }
  a:hover { text-decoration: underline; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<p>%s</p>
</body>
</html>`, title, html)
}
